### ISSUE TITLE
Doesn't run on php8.0

### ISSUE THREAD

**Issue by trint** [mix-php/bean#1]
[2020-11-28 17:18:06] MIX.ERROR: [Error.php:225] The @var annotation on Mix\Console\Error::dispatcher contains a non existent class "EventDispatcherInterface". Did you maybe forget to add a "use" statement for this annotation?
[code] 0 [type] PhpDocReader\AnnotationException
[file] in /var/www/work/vendor/mix/bean/src/PhpDocReader.php on line 115
 #0 Mix\Bean\PhpDocReader->getPropertyClass() in /var/www/vendor/mix/bean/src/BeanInjector.php on line 75
 #1 Mix\Bean\BeanInjector::inject() in /var/www/vendor/mix/bean/src/BeanFactoryTrait.php on line 140
 #2 Mix\Bean\ApplicationContext->newInstance() in /var/www/vendor/mix/bean/src/BeanFactoryTrait.php on line 90
 #3 Mix\Bean\ApplicationContext->getBean() in /var/www/vendor/mix/bean/src/ApplicationContext.php on line 36
 #4 Mix\Bean\ApplicationContext->get() in /var/www/vendor/mix/console/src/Application.php on line 127

**Comment by onanying** [comment]
你把 `manifest/beans/error.php` 文件的内容给我看一下，然后把你的 mix/mix-skeleton 骨架版本号发我，composer.lock 里面有当前使用的版本号
